---
title: "comm_doc"
output:
  word_document: default
  pdf_document: default
params:
  YYYYMMDD: YYYY-MM-DD
  workshop: (workshop)
  repo: (repo)
  repo_ref: (repo ref)
  location: (location)
  venue: (venue)
  time: (time)
  date: (date)
  workshop_website: (workshop website)
  workshop_website_url: (workshop website url)
  month: (month)
  day_of_workshop: (day of workshop)
  start_time: (start time)
  registration_page: (registration page)
  registration_page_url: (registration page url)
  setup_instructions: (setup instructions link)
  synopsis: (Evenbrite 140 characters)
  description: (Eventbrite longer description)
  syllabus: (syllabus)
  who: (audience)
  advertisement: (advertisement)
  set_title: (Communication doc)
  setup: (Software needed)
  file: (data.csv)
  lesson_url: (lesson URL)
  lesson_url_ref: (lesson URL ref)
  show_text: yes
---

---
title: `r params$set_title`
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## R Markdown

```

### Description  
### Title: `r params$workshop`  
`r params$date`, `r params$venue`  


### Eventbrite short description (140 characters)  
`r params$synopsis`
  
### Eventbrite long description (around 150 words)  
`r params$description`

The workshop is based on the teaching style of the Carpentries, and learners will follow along while the instructors write the code on screen. More information can be found on the `r params$workshop_website`.  
  
### Audience: 
The workshop is open and free to all researchers in the Netherlands at PhD candidate level and higher. We do not accept registrations by Master students. The workshop is aimed at PhD candidates and other researchers or research software engineers.  

### Prerequisite knowledge: 
`r params$who`

### Requirements: 
`r params$setup`

### Syllabus
`r params$syllabus`
  
------  

## Internal workshop announcement email  
#### Subject: Workshop announcement: `r params$workshop` in `r params$month`  

Hello,  

The Netherlands eScience Center is organising an online workshop in `r params$month`. The topic is “`r params$workshop`”. The workshop is open and free to all researchers in the Netherlands at PhD candidate level and higher. We do not accept registrations by Master students. 

**`r params$workshop`**  
`r params$date`  
`r params$time`, `r params$location`  
`r params$registration_page` [1]  

`r params$advertisement`

More information about this event can be found on the `r params$workshop_website` [2]. 

Who: `r params$who`
  

On behalf of the eScience Center Training Team,

Sacha van Breugel

  
Links  
[1] `r params$registration_page_url`  
[2] `r params$workshop_website_url`  

---  

## External workshop announcement email 
#### Subject: Workshop announcement: `r params$workshop` in `r params$month`

Hello,  

The Netherlands eScience Center is organising an online workshop in `r params$month`. The topic is “`r params$workshop`”. The workshop is open and free to all researchers in the Netherlands at PhD candidate level and higher. We do not accept registrations by Master students. 

**`r params$workshop`**  
`r params$date`  
`r params$time`, `r params$location`  
`r params$registration_page` [1]  

`r params$advertisement`

More information about this event can be found on the `r params$workshop_website` [2]. 

Who: `r params$who`

On behalf of the eScience Center Training Team,

Sacha van Breugel
  
  
Links  
[1] `r params$registration_page_url`  
[2] `r params$workshop_website_url`  

---

### First email to participants
#### Subject: `r params$workshop`: Setup instructions & Zoom link

Hello,

We are excited for the `r params$workshop` workshop on `r params$date`, and hope you are too. 

A few notes:

Be sure to complete this (pre-workshop survey)[pre-workshop survey] [1] by midday tomorrow. We use this to calibrate the pace of the workshop and, together with a post-workshop survey, to assess how it went.

Make sure you have the necessary software installed on your laptop by following the `r params$setup_instructions ` [2]. If you have any trouble, send us an email.

On the workshop days (`r params$date`), please join the call 15 minutes earlier (`r params$start_time`) if possible, to say hello to the instructors and fellow learners and to check if your audio and video setup works correctly. That will allow us to start teaching on time.

If you won’t be able to attend, please cancel your registration (by following instructions here [3])  so that we can offer your seat to someone on the waiting list.

Make sure to keep the `r params$workshop_website` [4] with all the necessary details handy.  

Join the workshop session with the following (Zoom link)[zoom link] [5]. Please make sure to log-in with the name you have used for the registration. For the safety reasons, people who cannot be recognised by the zoom user name will not be let into the workshop.

Let us know if you have any questions by emailing training@esciencecenter.nl. Otherwise, we will see you on `r params$day_of_workshop` from `r params$start_time`! 

Looking forward to seeing you soon!

On behalf of the eScience Center Training Team,

Sacha van Breugel


Links  
[1] [pre-workshop survey link]  
[2] `r paste0(params$workshop_website_url, '/#setup')`  
[3] https://www.eventbrite.com/support/articles/en_US/How_To/how-to-cancel-your-free-registration  
[4] `r params$workshop_website_url`  
[5] zoom link  

------

### Reminder message to attendees of the workshop
#### Subject: Reminder to attendees of the `r params$workshop`

Hello,

This is just a reminder for the [workshop title] workshop on `r params$date`.

If you won’t be able to attend, please cancel your registration (by following instructions [here](https://www.eventbrite.com/support/articles/en_US/How_To/how-to-cancel-your-free-registration) [1])  so that we can offer your seat to someone on the waiting list.

Looking forward to seeing you on `r params$day_of_workshop`!

On behalf of the eScience Center Training Team,

Sacha van Breugel

Links  
[1] https://www.eventbrite.com/support/articles/en_US/How_To/how-to-cancel-your-free-registration  

--------
### Email to participants after the workshop
#### Subject: A message to attendees of the `r params$workshop`
  
Hello,  

Thank you for attending our `r params$workshop` workshop this week. We hope that you had fun and learned a lot of useful skills. 

If you haven’t already, please be sure to complete our (post-workshop survey)[post-workshop survey] [1]. Your answers are essential to allow us to continuously improve our workshops for future learners.  
  
You will shortly be able to find all the notebooks and collaborative documents from the workshop in the files directory of the workshop repository [2]. All the lesson material used in the lesson can be found `r params$lesson_url_ref` [3].
  
If you have any other feedback about the workshop, or would like to get involved in organising workshops, please contact the eScience Center training team at training@esciencecenter.nl.  
  
You can also follow us on [Twitter](https://twitter.com/esciencecenter) [4]. We are continuously organising training events. You can find the list of upcoming events on the Center’s [website](https://www.esciencecenter.nl/digital-skills/) [5].  
  
We would also like to encourage you to subscribe to our [email updates](http://eepurl.com/dtjzwP) [6] and select an Invitation for Workshops option to get invited to training and related events organised by the Netherlands eScience Center.

On behalf of the eScience Center Training Team,

Sacha van Breugel

Links  
[1] [post-workshop survey link]  
[2] `r paste0(params$repo, "files")` 
[3] `r params$lesson_url`
[4] https://twitter.com/esciencecenter  
[5] https://www.esciencecenter.nl/digital-skills/ 
[6] http://eepurl.com/dtjzwP


