---
title: "planning_doc"
output: word_document
params:
  YYYYMMDD: YYYY-MM-DD
  sharepoint: [sharepoint]
  workshop_website: [workshop website]
  registration_page: [registration page]
  lead_instructor: [lead instructor]
  instructor: [instructor]
  helper: [helper]
  set_title: "Planning doc"
  file: data.csv
  show_text: TRUE
---

---
title: `r params$set_title`
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* Plan in Planner `r params$planner`` 
* Team Channel 
* `r params$sharepoint`
* `r params$workshop_website ` 
* Workshop Page Source 
* Lesson Content 
* Slides (optional) 
* `r params$registration_page`` 
* Collaborative Documents 1,2,3,4 
* Pre-workshop survey and results 
* Post-workshop survey and results 
* Debriefing document 
* Participants Spreadsheet 
* Zoom Link 

### Lead Instructor:  `r params$lead_instructor`

#### [Lead Instructor is an Instructor who is also responsible for some of the preparatory tasks as well as hosting most of the workshop. They also have the responsibilities of an Instructor (see below).]  

### Instructors:  `r params$instructor`

#### [An instructor is a person who teaches in the workshop. There must be two or more instructors (including the Lead Instructor) in every workshop. In the Carpentries workshops (Software Carpentry or Data Carpentry) at least one of the instructors needs to be certified by the Carpentries.]  

### Helpers: `r params$helper`

#### [Follow the chat and the collaborative document during the workshop, and answer participants’ questions. Also help them troubleshoot issues. They bring up questions to instructor’s attention if they think the question is relevant and timely]  
 

### Helper roles:  

#### Zoom host  

* Ensures all the Instructors and Helpers are co-hosts.  
* Lets people in from the waiting room, after checking if they are on the participants list.  
* Keeps the participants list updated.  
* Mutes and unmutes participants.  
* Keeps nonverbal feedback icons clean (lowers hands, etc).  
* Manages breakout rooms  
* Keeps an eye on the chat  
* Answers questions in the chat  
* Brings questions and issues to the attention of the teaching Instructor  
* Tells teaching Instructor when to slow down or speed up  

#### Note keeper:  
(ideally not the person who was teaching on that day)   

* Makes notes in the collaborative document  
* Makes the log of all commands typed in by the Instructor  
* Pastes exercises  
* Keeps collaborative document clean  

### Schedule & Teaching Division 

| Date | Lesson | Instructor | Designated Survivor | Zoom host | Note taker |
|---|---|---|---|---|---|
|   |   |   |   |   |   |  
    
	
## Calibration meeting (instructors + workshop coordinator, week before the workshop) 

### YYYY-MM-DD

### Roll Call 

#### Discussion Points & Notes 

* Pre-workshop survey 
* Welcome procedure 
* Review Tasks 

## Planning meeting (3 weeks before the workshop) 

### YYYY-MM-DD 

### Roll Call 

#### Discussion Points & Notes 

* Confirm the Lead Instructor (chairs the meeting)
* Assign note taker (one of the helpers)
* Select curriculum  
* Assign teaching  
* Assign helpers’ roles (designated survivor, Zoom Host, Note taker)  
* Assign Tasks in Planner, set deadlines. 
* Decide on setup sessions
* Additional pre-workshop survey questions needed?


